### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DartPower** [dpteam/AwesomeDPT-WindowsSoft#3]
- [x] Добавить https://openhardwaremonitor.org/files/openhardwaremonitor-v0.8.0-beta.zip
- [x] Добавить https://www.fosshub.com/InfraRecorder.html?dwl=ir053_x64.msi
- [x] Добавить https://vk.com/messenger
- [x] Добавить http://www.classicshell.net
- [x] Добавить https://www.microsoft.com/RU-RU/DOWNLOAD/confirmation.aspx?id=35
- [x] Добавить http://wincdemu.sysprogs.org/
- [x] Заменить OpenJDK на https://adoptopenjdk.net/
- [x] Добавить https://www.bleachbit.org/
- [x] Добавить https://github.com/oliverschwendener/ueli
- [ ] Внедрить в список два оптимизатора от DPT
- [x] Добавить https://github.com/Sycnex/Windows10Debloater
- [ ] Добавить VLC (Добавил MPV)
- [x] Добавить https://vk.com/tl_mc_launcher
- [ ] Добавить OCCT

**Comment by DartPower** [comment]
- Добавить @DartPower/LTSB-Add-MicrosoftStore

**Comment by DartPower** [comment]
* Добавить https://vk.com/messenger

**Comment by DartPower** [comment]
* Добавить http://www.classicshell.net

**Comment by DartPower** [comment]
* Добавить https://www.microsoft.com/RU-RU/DOWNLOAD/confirmation.aspx?id=35

**Comment by DartPower** [comment]
* Поправить ссылки

**Comment by DartPower** [comment]
* Добавить http://wincdemu.sysprogs.org/

**Comment by DartPower** [comment]
* Заменить OpenJDK на https://adoptopenjdk.net/
